version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - 127.0.0.1:8000:8000
    container_name: backend
    restart: on-failure